### ISSUE TITLE
Python3.9打包easyocr极其依赖后运行出错。

### ISSUE THREAD

**Issue by zhangbl-yh** [skywind3000/PyStand#10]
林爷您好，请教一个问题，我打包一个依赖easyocr的脚本后运行出错：
Python 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)] on win32

![image](https://user-images.githubusercontent.com/66652652/157681936-b2782729-eef3-45a4-8998-09a429e82236.png)

![image](https://user-images.githubusercontent.com/66652652/157682100-c4016481-7b53-4ac0-a13a-d240c6236560.png)

![image](https://user-images.githubusercontent.com/66652652/157682380-01138b08-be68-4be3-99e5-251c077dbee3.png)

我没使用您默认提供的3.8版本，是因为这个版本pip安装easyocr的时候会报依赖混乱的错误。操作系统是win10。
似乎在这个环境下，所有pyd格式的包都没法引入进来。用您提供的python3.8版本可以正常使用lxml，但是用我下载的3.9.9 embedded版本就不行，也会报类似的引包错误。

求指点。

**Comment by skywind3000** [comment]
PIL 包 import 出错吧，你得把 _image 那个 dll/pyd 弄过来啊。

**Comment by zhangbl-yh** [comment]
> PIL 包 import 出错吧，你得把 _image 那个 dll/pyd 弄过来啊。

![image](https://user-images.githubusercontent.com/66652652/157807877-42447092-5f98-458d-ae5a-3efc786ff1b4.png)
我是按照您的教程pip安装完了依赖，然后site-packages里面的东西全都拷贝过来了，pyd应该是我图中圈住的这个吧，但是还是提示import出错。

**Comment by skywind3000** [comment]
你安装 pip 那个 python 的版本和 pystand 里 embedded 的 python 版本一样吗？都是 64 位吗？

**Comment by zhangbl-yh** [comment]
> 你安装 pip 那个 python 的版本和 pystand 里 embedded 的 python 版本一样吗？都是 64 位吗？

是一样的，而且我特意在公司电脑和家里电脑都尝试了，都是同样的问题。而且我还尝试用3.9的embedded python先使用get-pip.py安装一下pip，然后用pip安装好所有的包，再拷贝site-packages里面的东西，这样也没有解决问题。

**Comment by skywind3000** [comment]
我稍后自己试试，你直接用 embedded 里面的 python.exe 启动行不行呢？

**Comment by zhangbl-yh** [comment]
> 我稍后自己试试，你直接用 embedded 里面的 python.exe 启动行不行呢？

我直接用embedded里的python.exe执行get-pip.py并安装依赖后，运行我的程序，能正常启动。

**Comment by skywind3000** [comment]
问题是 get-pip.py 把依赖安装到哪里了？

**Comment by zhangbl-yh** [comment]
> 

我是指直接用这个运行   python.exe /我脚本的路径.py  能运行，不使用PyStand。
get-pip.py 把依赖安装到了python.exe所在目录/Lib/site-packages。

**Comment by zhangbl-yh** [comment]
> 问题是 get-pip.py 把依赖安装到哪里了？

我是指直接用这个运行 python.exe /我脚本的路径.py 能运行，不使用PyStand。
get-pip.py 把依赖安装到了python.exe所在目录/Lib/site-packages。

**Comment by skywind3000** [comment]
试试最新版行不行：https://github.com/skywind3000/PyStand/releases/tag/1.0.6

注意，拷贝 PIL/Pillow 的时候，如果源 site-packages 下面有相关 `.pth` 文件，也一起拷贝过去。

**Comment by zhangbl-yh** [comment]
您这个更新解决了lxml没法引入的问题，但我的如下代码还是引入有问题。

def main():
    from PIL import ImageGrab, Image


https://github.com/zhangbl-yh/pydemo/upload
我上传了我的打包环境，您有空的时候可以看看，压缩分割成了12份。

**Comment by skywind3000** [comment]
你这个项目完全跑不起来，32 位的 PyStand.exe 没法加载 64 位的 python

**Comment by zhangbl-yh** [comment]
> 你这个项目完全跑不起来，32 位的 PyStand.exe 没法加载 64 位的 python

哦我确实不懂，我看release只有32位的我以为兼容64位。那看来我要想兼容64位python自己编译一个64位pystand就可以了。

非常感谢您的指点和解答。
