### ISSUE TITLE
如果上层目录是中文的话, 就会出错

### ISSUE THREAD

**Issue by linxy5211** [skywind3000/PyStand#11]
![image](https://user-images.githubusercontent.com/46511422/158081162-ac794fbe-23c3-4253-9f30-7783891508a0.png)

**Comment by skywind3000** [comment]
看这里：

https://github.com/skywind3000/PyStand/issues/6

**Comment by linxy5211** [comment]
谢谢大佬



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Linwei ***@***.***&gt;
发送时间: 2022年3月14日 06:21
收件人: skywind3000/PyStand ***@***.***&gt;
抄送: linxy5211 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [skywind3000/PyStand] 如果上层目录是中文的话, 就会出错 (Issue #11)





 
看这里：
 
#6
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
