### ISSUE TITLE
用户在Windows11下运行报错

### ISSUE THREAD

**Issue by xianyongjian080402** [skywind3000/PyStand#16]
用户是windows11系统
打开后报错：
![Uploading 316EE96AF6C59464CA5629159314BCF5.png…]()

**Comment by xianyongjian080402** [comment]
![316EE96AF6C59464CA5629159314BCF5](https://user-images.githubusercontent.com/70191815/167327154-6e3945c9-02dd-404b-9a96-a1d52de4f632.png)

**Comment by skywind3000** [comment]
是不是解压到包含中文路径的地方了？看这里：

https://github.com/skywind3000/PyStand/wiki/Frequently-Asked-Questions

**Comment by xianyongjian080402** [comment]
啊确实 解决了
十分感谢您分享这个项目
