### ISSUE TITLE
改为PyQt6后 报错： DLL load failed while importing QtCore: %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by xianyongjian080402** [skywind3000/PyStand#17]
![截屏2022-06-03 20 06 17](https://user-images.githubusercontent.com/70191815/171850280-d572ac13-8766-45b3-9574-84c17c2da923.png)
不知道 为什么 报了这个错

![截屏2022-06-03 20 06 58](https://user-images.githubusercontent.com/70191815/171850385-10ef77b9-9a34-4980-a67c-3b3811ad6050.png)

这个是我的import 我是特意用 虚拟机（win）来pip了一下
（我是在Mac上写的代码）

我把所有 在虚拟机里pip的下载的东西都放到了 指定目录 可是还不行

**Comment by skywind3000** [comment]
看一下 faq 里关于中文路径设置的问题是否类似，都和 qt dll 路径有关

**Comment by myd7349** [comment]
浏览了一下 https://github.com/xianyongjian080402/Minecraft-Optimal-Starter_issue/tree/master/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9 这个文件夹，猜测你这个程序需要使用 64 位的 Python 3.10。所以，尝试一下：

1. 将 PyStand 编译为 64 位的：

   ```
   > mkdir build
   > cmake .. -A x64
   > cmake --build . --config Release
   ```

2. 下载一个 64 位的 Python：

    https://www.python.org/downloads/release/python-3105/

**Comment by xianyongjian080402** [comment]
感谢
就是……我不方便打包 有好心人 能帮我打包吗
感谢感谢（不太了解 这个cmake，没用过 再加上我是Mac

**Comment by myd7349** [comment]
[PyStand-VS2022-x64.zip](https://github.com/skywind3000/PyStand/files/8874950/PyStand-VS2022-x64.zip)

**Comment by xianyongjian080402** [comment]
> 

感谢 感谢 太感谢了

**Comment by xianyongjian080402** [comment]
最近因为项目一直没发新版本 所以没测试打包

刚才测试了下
还是有问题
![截屏2022-06-21 01 19 05](https://user-images.githubusercontent.com/70191815/174651833-4ec090f3-9e17-40f1-aa98-5ba109c93265.png)

这个引用不知道为什么报错
![截屏2022-06-21 01 19 46](https://user-images.githubusercontent.com/70191815/174651920-ccd61c46-a68d-4952-beea-98407f02f4ea.png)

**Comment by xianyongjian080402** [comment]
![截屏2022-06-21 01 21 59](https://user-images.githubusercontent.com/70191815/174652166-52e24038-43e8-4642-a206-15bb422d4c4f.png)

我把这一行去了一下 还是不行

**Comment by xianyongjian080402** [comment]
https://github.com/xianyongjian080402/Minecraft-Optimal-Starter_issue/tree/master/2.0.3-alpha

我把文件放在这里了 大佬们可以看下

**Comment by xianyongjian080402** [comment]
感谢两位大佬
不过 我把pyqt6换成py3.8 之后 又遇到了问题

窗口不显示（PyStand那个exe用的是上面大佬帮我打包的64位的）


谢谢

https://github.com/xianyongjian080402/Minecraft-Optimal-Starter_issue/blob/master/2.0.3.zip
我压缩了 各位大佬可以下载 帮我看下

**Comment by xianyongjian080402** [comment]
感谢两位大佬
不过 我把用py3.10装的pyqt6换成py3.8 之后 又遇到了 窗口不显示（PyStand那个exe用的是上面大佬帮我打包的64位的）问题

https://github.com/xianyongjian080402/Minecraft-Optimal-Starter_issue/blob/master/2.0.3.zip
我压缩了 各位大佬可以下载 帮我看下

**Comment by xianyongjian080402** [comment]
就很奇怪
在我电脑上是可以的

**Comment by xianyongjian080402** [comment]
这几天在备考，终于有时间写代码了
**我昨天又试了下，我发现 在用命令行启动之后，过一会 就自动退出了（就是 那个exe退出了），正常情况下不会这样
但是pystand 没任何报错输出 所以我推测，肯定是报错了，但不知道为何，没有报错输出（前面那个引入的报错却能输出）**

很奇怪，我就在虚拟机上安装了py 运行了一下，果然，报错（但是在Mac上不报错，无语）

（那个报错我到现在也没找到原因，报错是又一个文件处理导致的，我用的os模块，创建一个文件，我打开参数写的是w

就是如果文件不存在，就创建，可是它给我报：找不到文件‘（路径）’ 我修复了半天，没用。最后我只能用try强行解决了）

**Comment by xianyongjian080402** [comment]
最后，是可以成功运行了 感谢各位大佬 @skywind3000 @myd7349 非常感谢这个项目
---
另外 @skywind3000  上面那个问题，能否修一下

**Comment by skywind3000** [comment]
哪个问题？修什么？

**Comment by xianyongjian080402** [comment]
这个
![截屏2022-07-09 00 47 41](https://user-images.githubusercontent.com/70191815/178035617-cf2eeb9d-d22a-490a-a6f5-4b4a1d1c8fe7.png)
我在虚拟机上安装py运行的时候是有报错输出的，但pystand没有

**Comment by myd7349** [comment]
@skywind3000 我大概明白 @xianyongjian080402 的意思了。我把 Release 里的 PyStand.int 修改了一下来复现 @xianyongjian080402 所说的问题。

```python
import sys
import os
import os.path

USE_PyQt6 = False
USE_EXCEPTHOOK = False

def except_hook(cls, exception, traceback):
    sys.__excepthook__(cls, exception, traceback)

if USE_EXCEPTHOOK:
    sys.excepthook = except_hook

if USE_PyQt6:
    from PyQt6.QtWidgets import *
    from PyQt6.QtCore import *
    print('Using PyQt6')
else:
    from PyQt5.QtWidgets import *
    from PyQt5.QtCore import *
    print('Using PyQt5')

def setfont(self):
    sys.stderr.write("This is stderr.\n")
    sys.stdout.write("This is stdout.\n")
    MOS_file_json = os.path.join(file,".MOS","MOS.json")  # <--- 在这里故意引入了一个错误：file 未定义，NameError）

app = QApplication([])

print('Setup UI...')

win = QWidget()
win.setWindowTitle('PyStand')

layout = QVBoxLayout()

label = QLabel('Hello, World !!')
if USE_PyQt6:
    label.setAlignment(Qt.AlignmentFlag.AlignCenter)
else:
    label.setAlignment(Qt.AlignCenter)
layout.addWidget(label)

fontComboBox = QFontComboBox()
fontComboBox.currentIndexChanged.connect(setfont)
fontComboBox.setCurrentIndex(0)
layout.addWidget(fontComboBox)

btn = QPushButton(text = 'PUSH ME')
layout.addWidget(btn)

win.setLayout(layout)
win.resize(400, 300)

print('Setup UI Done!')

btn.clicked.connect(lambda : [
        print('exit'),
        win.close(),
    ])

win.show()

if USE_PyQt6:
    app.exec()
else:
    app.exec_()

print('Exit!')

raise NameError('Goodbye!')
```

在信号处理函数 setfont 里引入了一个错误。

我在 Win10 上测试的结果如下：

1. 如果将 PyStand 编译为一个 GUI 程序，则从命令行中运行该程序时，这个错误并不会在屏幕上打印出来：

    > Using PyQt5
    > Setup UI...
    > This is stderr.
    > This is stdout.

2. 如果将 PyStand 编译为控制台程序，则可以看到槽函数里那个异常：

    > Using PyQt5
    > Setup UI...
    > This is stderr.
    > This is stdout.
    > Traceback (most recent call last):
    > File "C:\Users\myd7349\Downloads\PyStand-py38-pyqt5\PyStandCLI.int", line 26, in setfont
    >   MOS_file_json = os.path.join(file,".MOS","MOS.json")  # <--- 在这里故意引入了一个错误：file 未定义，NameError）
    >     NameError: name 'file' is not defined

StackOverflow 上有个问题：[PyQt: No error msg (traceback) on exit](https://stackoverflow.com/questions/33736819/pyqt-no-error-msg-traceback-on-exit)，其中提到：

> In PyQt v5.5 an unhandled Python exception will result in a call to Qt’s qFatal() function. By default this will call abort() and the application will terminate. Note that an application installed exception hook will still take precedence.

所以，要想让 PyQt 中的异常在控制台输出，可以考虑将 PyStand 编译为控制台程序。或者是，在脚本中加入：

```python
import sys

def except_hook(cls, exception, traceback):
    sys.__excepthook__(cls, exception, traceback)

sys.excepthook = except_hook
```

这样，即使将 PyStand 编译为 GUI 程序，也可在命令行中看到 PyQt 相关的异常：

> Setup UI...
This is stderr.
This is stdout.
Traceback (most recent call last):
  File "C:\Users\myd7349\Downloads\PyStand-py38-pyqt5\PyStand.int", line 26, in setfont
    MOS_file_json = os.path.join(file,".MOS","MOS.json")  # <--- 在这里故意引入了一个错误：file 未定义，NameError）
NameError: name 'file' is not defined
Setup UI Done!
exit
Exit!
Traceback (most recent call last):
  File "<string>", line 34, in <module>
  File "C:\Users\myd\Downloads\PyStand-py38-pyqt5\PyStand.int", line 71, in <module>
    raise NameError('Goodbye!')
NameError: Goodbye!

**Comment by xianyongjian080402** [comment]
OK呀 谢谢谢谢 已经解决了
