### ISSUE TITLE
运行含有中文的源文件存在问题

### ISSUE THREAD

**Issue by danielweiv** [skywind3000/PyStand#2]
创建一个python文件，内容写‘print('视频预览')’，运行报错：
  File "<string>", line 26, in <module>
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 11: illegal multibyte sequence

**Comment by skywind3000** [comment]
你不要把中文内容放在 `PyStand.int` 里，不要什么都往里面塞，把 `PyStand.int` 当作一个入口，去 import 你的主程序去，要写什么，写在你的主程序里。

**Comment by danielweiv** [comment]
将文件由utf8编码改为ansi编码，错误消失

**Comment by danielweiv** [comment]
> 你不要把中文内容放在 `PyStand.int` 里，不要什么都往里面塞，把 `PyStand.int` 当作一个入口，去 import 你的主程序去，要写什么，写在你的主程序里。

收到，import后可以正常运行
