### ISSUE TITLE
PyQt5 QtWidgets.QFileDialog.getOpenFileName 卡死或程序闪退

### ISSUE THREAD

**Issue by ConyKitty** [skywind3000/PyStand#23]
使用PyQt5, 主窗体调用子窗体时，子窗体上有个按钮，点击会打开选择文件的对话框，`QtWidgets.QFileDialog.getOpenFileName`在embedable Python环境运行，子窗体弹出正常，但程序在运行到`getOpenFileName(self, 'title',path)`时会卡死，程序无响应，即使在powershell中运行PyStand.exe也看不到报错信息。而在常规的Python环境中，运行OK，对话框正常弹出，可选择文件。
怀疑是缺少了哪个库，或者哪个库安装异常？之前发现embed Python没有tkinter，后来把文件拷贝进去了。这里请教下pywin32模块如何安装到embedable Python环境，直接从虚拟环境中site-packages拷贝到到embed 的site-packages就可以吗？

**Comment by skywind3000** [comment]
你试试完整版，release 里面那个  PyStand-py38-pyqt5.7z ，

不排除哪个文件被我删除多了，如果还不行，麻烦贴一下最简单的复现程序。

**Comment by ConyKitty** [comment]
您好，谢谢回复。 试了release的完整的包,还是有这个问题，应该不是PyQt被过度修建，我之前也是copy的完整的PyQt安装包。
我用PyStand-py38-pyqt5.7z， 装上了pip，把依赖库用pip重新安装了一遍，还是到了弹出对话框这一步闪退。
之前我用的py36，出现这个问题后，Dialog从QT替换到tkinter的对话框，可以正常弹出，上午按照您说的用PyStand-py38-pyqt5.7z，结果QT和tkinter的两个对话框都不能正常弹出，都闪退。是不是embed Python env调用windows 平台的相关接口，在哪里被阉割了。。下面是复现的代码片段, 一个窗框上点击按钮直接弹出个选择文件对话框：

Tkinter filedialog:

```python
def show_config(self):
        self._root = tk.Tk()
        self._root.withdraw()
        start_path = r'D:\config_path'
        if not os.path.isdir(start_path):
            os.mkdir(start_path)
        file_path = filedialog.askopenfilename(initialdir=start_path,
                                               title=caption,
                                               filetypes=(("config files", "*.ini"),
                                                          ("all files", "*.*")))
```

PyQt QFileDialog.getOpenFileName

```python
def show_config(self):
        start_path = r'D:\config_path'
        if not os.path.isdir(start_path):
            os.mkdir(start_path)
        file = QtWidgets.QFileDialog.getOpenFileName(self, caption, start_path,
                                                     'Config File (*.ini)')
        print(file)
```

补充下我的运行环境：

-Win11 Pro	10.0.22000 版本 22000
- PyStand Embeddable Python 3.6 32bit (Tkinter dialog OK, PyQt dialog Fail)
- PyStand Embeddable Python 3.8 32bit(Tkinter dialog Fail, PyQt dialog Fail)

**Comment by skywind3000** [comment]
奇特，我有空看看

**Comment by myd7349** [comment]
我用如下脚本在 Win10 上做了一下测试（用该脚本替换掉 PyStand-py38-pyqt5.7z 中的 PyStand.int），没能重现：

```python
#  vim: set ts=4 sw=4 tw=0 et ft=python :
import sys, os
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *

def except_hook(cls, exception, traceback):
    sys.__excepthook__(cls, exception, traceback)

sys.excepthook = except_hook

def show_config():
    start_path = r'D:\config_path'
    if not os.path.isdir(start_path):
        os.mkdir(start_path)
    file = QFileDialog.getOpenFileName(None, 'Select a config file:', start_path,
                                       'Config File (*.ini)')
    os.MessageBox(file)

app = QApplication([])

win = QWidget()
win.setWindowTitle('PyStand')

layout = QVBoxLayout()

label = QLabel('Hello, World !!')
label.setAlignment(Qt.AlignCenter)
layout.addWidget(label)

btn = QPushButton(text = 'PUSH ME')
layout.addWidget(btn)

win.setLayout(layout)
win.resize(400, 300)

btn.clicked.connect(lambda : [
        show_config(),
    ])

win.show()

app.exec_()
```

可以把如下代码加到启动脚本里，这样在命令行下应该就可以看到 Qt 的错误输出了：

```python
def except_hook(cls, exception, traceback):
    sys.__excepthook__(cls, exception, traceback)

sys.excepthook = except_hook
```

**Comment by ConyKitty** [comment]
结论：导入clr引起

您好， 打印错误的函数`except_hook`非常有帮助，可以看到很多之前发现不了的错误，比如抓到了安装的tkinter不兼容，对话框会报错。但是依旧无法抓到PyQt弹框卡死问题。而且确认了和子窗体无关，直接按钮绑定弹出选文件的对话框也是有问题。
后来，我逐一精简代码，发现问题是由于项目中的几个引用导致。这两个import，有导入其中任意一个，就会在弹出QT对话框时卡死。
```python
from moduleA import ClassA
from folderB.moduleB import ClassB
```
项目的目录如下， 省略了部分文件：

> PyStand_Folder\\Projects\\ProjectA
│  main.py
│  image_rc.py
│  moduleA.py
│  tool_box.py
│
├─folderB
│  │  moduleB.py
│
├─UI
│  │  ui_About.py
│  │  ui_config_window.py
│  │  ui_main_window.py
│  │
│  ├─Image
│  │      Logo.ico

在根目录PyStand_Folder\

│  PyStand.exe
│  PyStand.int

PyStand.int中添加了系统路径 `PyStand_Folder\\Projects\\ProjectA`

引用的moduleA和moduleB中也没有循环引用，毕竟在非embable Python环境中运行良好。然后定位到 moduleB中有个引用，`from packageA.moduleC imoprt ClassC`， 这个库是个自己打包的库，已经放到了site-packages文件夹，然后moduleC中又有一个自己打包的PackageB, 导入`from packageB.moduleD import ClassD`, 其中moduleD中引用了`clr`, Embedable Python环境中无法调用DotNet嘛。再深入就不太懂了，这个限制您帮忙看看有没办法解决呢。
这个问题找到了，不是PyStand项目的问题，所以这个问题先关掉了。多谢支持

**Comment by myd7349** [comment]
如果是 `import clr` 导致的话，有可能是某个模块依赖了 [```pythonnet```](https://github.com/pythonnet/pythonnet)。我回头可以做个测试。
