### ISSUE TITLE
如果要支持linux，怎么实现？

### ISSUE THREAD

**Issue by aihuasxy** [skywind3000/PyStand#3]

**Comment by albertofwb** [comment]
同样的思路 这个项目主要是做了一个启动器，并且设置了一些房间变亮。将代码里的 win32API替换成linux的应该就可以了

或者直接写一个脚本。

**Comment by skywind3000** [comment]
appimage 啊。

**Comment by LeeMoonCh** [comment]
> 继续写个壳，然后 appimage 啊，把独立的 python 和依赖，还有 libc, libstdc++ 之类的封装进去，做一个 linux 通用版即可，跟 go 语言一样，下载下来就能运行。

能理解成，将pyStand.exe 使用pyStand.sh实现，脚本中调用pyStand.py的同名文件这样子把？
