### ISSUE TITLE
请教: 把 .py 先转换成 .pyc 再压缩成 script.egg  这步怎么做？

### ISSUE THREAD

**Issue by zuowanbushiwo** [skywind3000/PyStand#34]
@skywind3000 
     大佬，想做一个基础加密功能，看了你的知乎文章，没看懂，能详细指导一下吗？
     我搜索了一下是这样做吗？没找到详细的制作步骤。
    https://blog.csdn.net/weixin_39639049/article/details/111425982
    https://stackoverflow.com/questions/2051192/what-is-a-python-egg 
谢谢！

**Comment by zhang-weiyu** [comment]
`.pyc`可以使用python自带的模块, 单py文件可以使用
`python -m py_compile "要编译的py文件路径"`
多文件在一个目录下可以使用
`python -m compileall "要编译的目录路径"`

执行完之后会在同级目录生成`__pycache__`文件夹, 该文件夹内为编译得到的`.pyc`文件

**Comment by zuowanbushiwo** [comment]
好的，感谢回复！
