### ISSUE TITLE
【求助】单独运行PyStand.exe时闪退

### ISSUE THREAD

**Issue by gkt-cn** [skywind3000/PyStand#37]
韦神您好，

感谢您提供的PyStand，真的很喜欢。但是最近遇到了一些问题，无法解决，还望帮忙看看。

我目前的平台是windows x64+PyStand x64，用命令行运行没有问题，也没有错误提示。但是在双击直接运行PyStand.exe的时候会发生闪退（也即会闪出一个命令行的窗口，然后立即消失）。

经过定位，发现是由于
from paddlespeech.cli.asr.infer import ASRExecutor
这句话导致的。如果把这句话注释掉则没有问题可以执行。

后来我把这句话放到了您给的示例文件中，也是一样的效果，同样会发生闪退。

由于没有任何错误信息出现，所以也没有办法排查到底是哪里的问题，还希望韦神和其他大佬看到后能够帮我分析一下。

谢谢！

**Comment by myd7349** [comment]
猜测这个问题和 #38 有一定的相似性。

https://github.com/skywind3000/PyStand/issues/38#issuecomment-1434394021

**Comment by gkt-cn** [comment]
> 

您好，因为我没有编译经验，不知道您能否提供一份编译好的exe文件，最好是64位的，谢谢啦。

**Comment by myd7349** [comment]
[PyStand-x64.zip](https://github.com/skywind3000/PyStand/files/10776335/PyStand-x64.zip)

这里边提供了四个版本的 PyStand x64：
- PyStand-x64-Test GUI 版 + 命令行版
  - 编译自 https://github.com/myd7349/PyStand/commit/1fdae5913a12faaf97c8fa7dd157186a68a5fdde
- PyStand-x64 GUI 版 + 命令行版
  - 编译自 https://github.com/skywind3000/PyStand/pull/39

**Comment by skywind3000** [comment]
@gkt-cn ，麻烦测试下上面这个版本

**Comment by gkt-cn** [comment]
> [PyStand-x64.zip](https://github.com/skywind3000/PyStand/files/10776335/PyStand-x64.zip)
> 
> 这里边提供了四个版本的 PyStand x64：
> 
> * PyStand-x64-Test GUI 版 + 命令行版
>   
>   * 编译自 [myd7349@1fdae59](https://github.com/myd7349/PyStand/commit/1fdae5913a12faaf97c8fa7dd157186a68a5fdde)
> * PyStand-x64 GUI 版 + 命令行版
>   
>   * 编译自 [Fix #38 #39](https://github.com/skywind3000/PyStand/pull/39)



> @gkt-cn ，麻烦测试下上面这个版本

两位大佬，试了一下，的确是同样的问题。目前用 @myd7349 的两个版本中，PyStand-x64的两个版本已无问题，可以运行；PyStand-x64-Test的CLI版本没问题，但GUI报错，截图如下：

![QQ截图20230219221048](https://user-images.githubusercontent.com/50159147/219953754-b99ed860-753b-4874-898b-853d9c7a3a3b.png)

![QQ截图20230219221111](https://user-images.githubusercontent.com/50159147/219953760-609f3373-e0d3-4129-b031-307dd0351241.png)

**Comment by gkt-cn** [comment]
> @gkt-cn ，麻烦测试下上面这个版本

顺便再反馈一下，用 @skywind3000 韦神您的x64版本必须要用稍微老点的PyQT5才行（比如5.15.0），最新版也是有问题的，无法导入PyQT里面的模块。

**Comment by skywind3000** [comment]
你说的是哪个 python 版本，配哪个新的 PyQT ？

**Comment by gkt-cn** [comment]
> 你说的是哪个 python 版本，配哪个新的 PyQT ？

就是您打包好的x64，python是3.8.10。PyQT我试的是最新版的PyQT5是不行的，但是5.15.0可以。

**Comment by skywind3000** [comment]
如果你不考虑 win7 兼容性的话，直接用 python3.11 吧。

**Comment by skywind3000** [comment]
麻烦测试下最新的 1.0.10 还会闪退吗？ok 的话我就先关了这个 issue

**Comment by gkt-cn** [comment]
> 麻烦测试下最新的 1.0.10 还会闪退吗？ok 的话我就先关了这个 issue

不闪退了，写写两位
