### ISSUE TITLE
在不启用 -DPYSTAND_CONSOLE=ON 的时候，python 代码里的 sys.stdout.write 操作会让程序自动退出。

### ISSUE THREAD

**Issue by hfchen-psee** [skywind3000/PyStand#38]
具体测试情况
- 资源管理器双击 exe， 失败
- cmd 中运行 exe， 成功

**Comment by skywind3000** [comment]
我这边没问题。
你贴一下 PyStand.int 这个入口脚本的内容，尽量删除无关代码，最小化复现。

**Comment by hfchen-psee** [comment]
我这儿可以用 PyStand-py38-pyqt5-lite 里面的例子[PyStand.txt](https://github.com/skywind3000/PyStand/files/10764230/PyStand.txt)复现。
直接加一句 `sys.stdout.write('_lib_path\n')` 就够了。

**Comment by myd7349** [comment]
我测了一下：https://github.com/myd7349/PyStand/tree/issue-38 。

在 GUI 模式下，不从控制台开你这个程序的话，AttachConsole 会失败，进而导致 PyStand 中内嵌的启动代码中的 stdout & stderr 重定向抛出异常。

用我魔改过的代码会看到：

![图片](https://user-images.githubusercontent.com/5435649/219608594-146d9776-f1d6-461b-b320-bf76712771df.png)

![图片](https://user-images.githubusercontent.com/5435649/219608628-a87d9935-9574-429e-9b6b-2ec0fc0b56df.png)

**Comment by hfchen-psee** [comment]
个人还是倾向于方案一，想看输出从 console 启动好了。双击跳出一个 console 看着碍眼，当然从命令行参数关掉 console 也行。

**Comment by skywind3000** [comment]
倾向于方案1，不要加 log 了，真要加 log 的程序，一般会自己初始化 logging 库来做的。
