### ISSUE TITLE
由于 Exception.ToString() 失败，因此无法打印异常字符串。

### ISSUE THREAD

**Issue by ConyKitty** [skywind3000/PyStand#4]
将一个PyQt 5的项目添加到了script 文件夹下，在PyStand.int 中引入，然后在terminal中启动PyStand.exe. 跟句错误提示，缺什么就从Python环境的site-package 中拷贝对应的库到PyStand 的site-package 。前面几个库放进去就好了，然后遇到了这个错误，请问怎么解决啊，怎么能看到是哪里引发的错误

> PS D:\PyBuild\pystand>.\PyStand.exe
> 由于 Exception.ToString() 失败，因此无法打印异常字符串。

Python: 3.6.2 32 bit
PyStand: 32 bit

**Comment by ConyKitty** [comment]
可能是某个引用导致的，在script里的脚本中，注释掉了一些引用，能启动了，界面弹出，但是点按钮运行后，程序还是不能正常运行，直接关掉了，没有任何提示。
怎样才能让标准输出流打印更多的错误信息呢？或者怎么样能提示更多的错误信息？

**Comment by skywind3000** [comment]
你用的 pystand 是哪个版本的？最早的有个小问题被我修复了。
release 里重新下载个最新的 pystand 的 exe 试试

**Comment by ConyKitty** [comment]
> 你用的 pystand 是哪个版本的？最早的有个小问题被我修复了。 release 里重新下载个最新的 pystand 的 exe 试试
pystand 用CMake编译出来的。运行 int 的代码没有问题了，后来打包egg有问题，先把这个issue关掉了。

**Comment by skywind3000** [comment]
https://github.com/skywind3000/PyStand/issues/5#issuecomment-1048697436

egg 打包参考这里
