### ISSUE TITLE
关于目录结构的一些小建议

### ISSUE THREAD

**Issue by yunluo** [skywind3000/PyStand#43]
你好，目前的readme里面提到的结构是runtime，site-packages 文件夹，看了下代码实际site-packages可以改为lib的，runtime能不能也支持多个命名，比如 增加 bin，在做的项目里面规则是bin，lib目录，主要是方便不熟悉Python的其他朋友了解目录是干啥的，自己改了下编译了一个，老板看要不要更新下呢

**Comment by skywind3000** [comment]
不更新，site-packages 是 python 里的标准用于，第三方库的安装位置，而 lib 文件夹是自己的库，我自己还有很多自己的 lib 要放到 lib 目录，不能和 site-packages 搞混了。

再，bin 是 unix 的习惯，不是 windows 的习惯，windows 程序不用 bin 目录；而且一个项目有 bin 目录时，我会下意识的到 bin 下面去找可执行文件，但是项目的 PyStand 可执行却在顶层，这个有认知上的一个误导。
