### ISSUE TITLE
int文件是否也能直接省略呢？

### ISSUE THREAD

**Issue by yunluo** [skywind3000/PyStand#48]
最近在使用pystand部署程式，发现int其实也不是必须要的嘛，

作者文档里面写的，int文件要尽量简单，我目前也是这样做的，基本就是这样
```
import main
main.main()
```
我寻思着，就这2行代码，也占用一个文件，有点多余了，是否可以这样

1. 默认寻找 pystand.exe同名int文件，
2. 没有再找_pystand_static.int文件
3. 都没有的话，直接执行以下代码
```
import main
main.main()
```
或者其他类似导入代码
```
import app
app.run()
```

**Comment by skywind3000** [comment]
省不了，因为 PyStand.int 里可以做很多加载相关的事情，比如判断并加载 main 的 egg 文件，
分别针对开发模式和发布模式对应不同的加载策略。

这部分代码变来变去，集成到 exe 里不方便，所以放出来。

**Comment by yunluo** [comment]
> 省不了，因为 PyStand.int 里可以做很多加载相关的事情，比如判断并加载 main 的 egg 文件， 分别针对开发模式和发布模式对应不同的加载策略。
> 
> 这部分代码变来变去，集成到 exe 里不方便，所以放出来。

> 省不了，因为 PyStand.int 里可以做很多加载相关的事情，比如判断并加载 main 的 egg 文件， 分别针对开发模式和发布模式对应不同的加载策略。
> 
> 这部分代码变来变去，集成到 exe 里不方便，所以放出来。

我承认我有点标题党了

你的意思我清楚，我的意思是在原来的逻辑上增加一个情况而已，并不是要取消int文件，当有int文件按照int文件的代码执行，没有int文件再直接执行上面的代码。

就好像有配置文件就读取配置文件内容，没有就使用默认的启动方式。目前我自己修改了代码，能够执行默认导入函数执行，但是c不太熟悉，可能不太好，所以还是反馈到这里。
