### ISSUE TITLE
程序路径不能包含中文

### ISSUE THREAD

**Issue by alayamanas** [skywind3000/PyStand#6]
感谢作者分享这个方便的打包工具，我用来给非技术同事写一些方便的小工具。
但使用过程中遇到一点问题，PyStand.exe的路径中不能包含中文（我知道只要换成纯英文路径就行了，但实在是被问多了😂），请教下有什么办法能解决这个问题么？
<img width="360" alt="微信截图_20220227163537" src="https://user-images.githubusercontent.com/10472264/155875180-4426ca57-65f8-4773-99da-ceb3f651d7e7.png">

**Comment by skywind3000** [comment]
这恐怕是 Qt 的限制吧，不是 PyStand 的锅，或者可以在 PyStand.int 里先检测下，如果中文路径就把 Qt 库拷贝到其它地方，并加入 sys.path

**Comment by skywind3000** [comment]
或者换成 PySide 试试？用那个 QtPy 的包做兼容

**Comment by qyw233** [comment]
但是好像别的打包工具出来完全没有这个问题啊，比如nutika

**Comment by alayamanas** [comment]
> 或者换成 PySide 试试？用那个 QtPy 的包做兼容

好主意，我改天试试pyside2

**Comment by skywind3000** [comment]
@qyw233 因为 nutika 或者 PyInstaller 每次运行都要把所有文件解压到一个临时目录（英文路径）再运行，所以没有这个问题：

- https://www.zhihu.com/question/48776632/answer/2336654649

问题是你确定要 PyInstaller/nutika 这种又慢又臃肿的打包方式么？你就是 ssd 够快，每次运行解压出几十个文件来，然后让 Windows Defender 全部扫描一次才能真正开始。

想想都头大，你即便开头检测发现中文路径，然后自己拷贝一下 Qt 的动态库，也只是仅仅碰到中文路径的时候需要拷贝，并且是第一次运行的时候需要拷贝，后面就复用了，根本用不着跟 PyInstaller/nutika 那种不管什么情况，每次解压，运行完又删除的策略一样。

**Comment by myd7349** [comment]
##### 概述
已重现该问题。重现方式：
- 从 PyStand release 页面下载 PyStand-py38-pyqt5-lite.7z（PyStand-py38-pyqt5.7z）；
- 将其解压至 `PyStand-py38-pyqt5-lite` 文件夹下，并重命名该文件夹为 `测试 PyStand-py38-pyqt5-lite`；
- 双击 PyStand.exe 启动，发现弹出如上错误对话框；

经过测试，我发现两种有效的解决方案。这两种解决方案都是通过修改 `PyStand.int` 文件以解决中文带来的乱码问题导致 platform plugins 无法正确加载的问题。

##### 问题原因
路径中包含中文会导致无法找到 platform plugins。

##### 解决方案一
```python
#  vim: set ts=4 sw=4 tw=0 et ft=python :
import sys, os
import os.path

os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = r'.\site-packages\PyQt5\Qt5\plugins'  #### 这一行是新增的。用的是相对路径。

from PyQt5.QtCore import *
from PyQt5.QtWidgets import *

app = QApplication([])
```

##### 解决方案二
```python
#  vim: set ts=4 sw=4 tw=0 et ft=python :
import sys, os
import os.path

from PyQt5.QtCore import *
QCoreApplication.addLibraryPath(r'.\site-packages\PyQt5\Qt5\plugins')  #### 这一行是新增的。用的是相对路径。

from PyQt5.QtWidgets import *

app = QApplication([])
```

**Comment by alayamanas** [comment]
> ##### 概述
> 已重现该问题。重现方式：
> 
> * 从 PyStand release 页面下载 PyStand-py38-pyqt5-lite.7z（PyStand-py38-pyqt5.7z）；
> * 将其解压至 `PyStand-py38-pyqt5-lite` 文件夹下，并重命名该文件夹为 `测试 PyStand-py38-pyqt5-lite`；
> * 双击 PyStand.exe 启动，发现弹出如上错误对话框；
> 
> ##### 问题原因
> 路径中包含中文会导致无法找到 platform plugins。可以在 `PyStand.int` 开头加入如下代码：
> 
> ```python
> #  vim: set ts=4 sw=4 tw=0 et ft=python :
> import sys, os
> import os.path
> 
> from PyQt5.QtCore import *
> 
> os.MessageBox(QTextCodec.codecForLocale().name())
> os.MessageBox('Qt5 Plugins path: {0}'.format(QLibraryInfo.location(QLibraryInfo.PluginsPath)))
> ```
> 
> 你会发现，中文路径中的汉字经过 GBK 编码又被 Qt 以 Latin-1 解码：
> 
> ```
> >>> '测试'.encode('gbk').decode('latin_1')
> '²âÊÔ'
> ```
> 
> 经过测试，我发现两种有效的解决方案。这两种解决方案都是使用相对路径来绕过中文路径带来的问题。
> 
> ##### 解决方案一
> ```python
> #  vim: set ts=4 sw=4 tw=0 et ft=python :
> import sys, os
> import os.path
> 
> os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = r'.\site-packages\PyQt5\Qt5\plugins'  #### 这一行是新增的。用的是相对路径。
> 
> from PyQt5.QtCore import *
> from PyQt5.QtWidgets import *
> 
> app = QApplication([])
> ```
> 
> ##### 解决方案二
> ```python
> #  vim: set ts=4 sw=4 tw=0 et ft=python :
> import sys, os
> import os.path
> 
> from PyQt5.QtCore import *
> QCoreApplication.addLibraryPath(r'.\site-packages\PyQt5\Qt5\plugins')  #### 这一行是新增的。用的是相对路径。
> 
> from PyQt5.QtWidgets import *
> 
> app = QApplication([])
> ```

非常感谢你！

**Comment by skywind3000** [comment]
帅.

你可以用直接路径，从 PyStand 里面取出 __file__ 来：

```python
HOME = os.path.dirname(os.path.abspath(__file__))
```

**Comment by qyw233** [comment]
感谢各位大佬，不过还有一点问题，就是使用QtWebEngine的时候上述方法还是不太可以，甚至连错误都没有报，不知道为啥

**Comment by skywind3000** [comment]
最新的 PyQt5 已经不包含 QtWebEngine 了，你要单独安装

    pip install PyQtWebEngine

**Comment by qyw233** [comment]
我已经把包括那个PyQtWebEngine全部拷贝过去了，在英文路径的时候一切正常，但是就是不能运行中文，甚至在解决上面那个plugins问题之后没有报错程序就关闭了

**Comment by skywind3000** [comment]
实在不行，那你就在 pystand.int 里面检测下中文路径，然后把 dll/pyd 拷贝到某个地方，设置 sys.path 再 import 呗

**Comment by qyw233** [comment]
主要是他连错误都不报，不知道要拷贝啥，如果是用pyinstall打包的exe他会报错找不到啥把相应文件拷到和exe的同一目录就可以。但是同样的文件拷贝在这里还是不行并且不报任何错

**Comment by simpleowen** [comment]
不一定是中文路径会导致这个问题，我在 64 位 Win7 纯英文路径下也遇见这个问题。

**Comment by balllei** [comment]
CMake的时候，出这个问题CMake Error: CMAKE_RC_COMPILER not set, after EnableLanguage，请问各位大佬怎么解决啊
