### ISSUE TITLE
导入ddddocr报错

### ISSUE THREAD

**Issue by AstronW** [skywind3000/PyStand#60]
系统 win10 LTSC
ddddocr版本 1.4.8
onnxruntime版本 1.15.1
我把所有的包全都复制到了site-packages下，运行时就会报错
![image](https://github.com/skywind3000/PyStand/assets/56785096/6b39f481-8046-4585-9920-b81558ec38f5)
onnxruntime文件夹下有onnxruntime_pybind11_state.pyd这个文件，看起来好像是应用程序找不到或处理不了这个文件，请问大佬应该怎么解决

> onnxruntime
> │  
> ├─capi
> │  │  onnxruntime_collect_build_info.py
> │  │  onnxruntime_inference_collection.py
> │  │  onnxruntime_providers_shared.dll
> │  │  onnxruntime_pybind11_state.pyd
> │  │  onnxruntime_validation.py
> │  │  version_info.py
> │  │  _ld_preload.py
> │  │  _pybind_state.py
> │  │  __init__.py
> │  │  
> │  └─training

**Comment by AstronW** [comment]
之前的问题好像时因为pip时使用的python版本和runtime中的python版本不同导致的，现在在import numpy的时候又出现了新的问题
python版本为 3.11
numpy的版本为 1.26.1
![image](https://github.com/skywind3000/PyStand/assets/56785096/0a9ec05b-647d-4f66-9322-f4f371078c43)

**Comment by skywind3000** [comment]
注意，连 site-packages 中的 .pth , ._pth 文件一起复制过去。
