### ISSUE TITLE
加入numpy包的时候出现错误

### ISSUE THREAD

**Issue by whitecateattea** [skywind3000/PyStand#61]
请教一下，在site-packages中加入numpy时，出现如下错误，好像是路径的问题，但是在环境中调试时是正常的
![image](https://github.com/skywind3000/PyStand/assets/84962783/aedadaa8-897d-46c4-80d4-ed2374c09817)

**Comment by skywind3000** [comment]
你拷贝的时候没拷贝完吧？

**Comment by whitecateattea** [comment]
> 你拷贝的时候没拷贝完吧？

我一开始也是怀疑，所以我所幸就先把所有的package都复制进去了，然后也不行

**Comment by skywind3000** [comment]
版本不对？64 位和 32 位？

**Comment by whitecateattea** [comment]
应该不是，如果不导入这个包就没问题，我在script中写了一个最简单的main函数，只要引入numpy就不行
```
import os
import sys
import numpy as np

def main():
    matrix_ = np.zeros(3)
```

**Comment by skywind3000** [comment]
.pth 文件也拷贝过去了？

**Comment by whitecateattea** [comment]
我复制了所有的内容，pth指的是这个文件吗
![image](https://github.com/skywind3000/PyStand/assets/84962783/6c2160fe-97a7-4445-a610-4772bfc1b81b)
他里面的内容是这样的
`import os; var = 'SETUPTOOLS_USE_DISTUTILS'; enabled = os.environ.get(var, 'local') == 'local'; enabled and __import__('_distutils_hack').add_shim(); 
`

**Comment by skywind3000** [comment]
https://github.com/skywind3000/PyStand/issues/60

**Comment by whitecateattea** [comment]
感谢您的耐心帮助，我成功解决了问题。

**Comment by skywind3000** [comment]
咋解决的？给其他类似的人留点线索啊

**Comment by user-et** [comment]
大佬，我也遇到了一样的问题，能请教下是怎么解决的吗？ @whitecateattea
