### ISSUE TITLE
将runtime换成python3.10版本无法运行

### ISSUE THREAD

**Issue by dollarfunc** [skywind3000/PyStand#63]
大佬，我下载的PyStand-py38-pyqt5，直接点击可以运行，但是将runtime换成python-3.10.11-embed-win32，报错，
![屏幕截图 2023-12-01 172942](https://github.com/skywind3000/PyStand/assets/138861697/20453420-583e-4fe9-b214-16cae5256632)
是不可以换成其他版本么？但是我的程序只能在3.10版本运行，麻烦大神了！

**Comment by hiroi-sora** [comment]
Release里的 PyStand-py38-pyqt5 应该是32位的，你如果替换成64位的 3.10 当然无法运行。

你可以下载 PyStand-py38-x64.7z ，这个是64的。然后再替换3.10试试。

**Comment by hiroi-sora** [comment]
你好。我复现了你的问题，并通过重新下载适用于3.10的PyQt5包解决了。

步骤：
1. 下载适用于3.10的PyQt5发行包：
```
pip download PyQt5 --python-version 3.10  --platform win32 --only-binary=:all:
```

2. 下载了多个whl文件。用压缩软件打开它们，将其中的`PyQt5`目录解压，并放在一起。（所有whl解压出来的东西要混在一起。）
3. 在PyStand自带的site-packages目录中，删除原PyQt5，将新下载的PyQt5放进去。

经过上述步骤，我用跟你一样的python版本，能够正常运行。

**Comment by dollarfunc** [comment]
哇，原来您是[Umi-OCR](https://github.com/hiroi-sora/Umi-OCR)的作者啊！久仰久仰！
