### ISSUE TITLE
如何解决multiprocessing导入时无限开启进程？

### ISSUE THREAD

**Issue by zty1122zty** [skywind3000/PyStand#67]
在pyinstaller打包pyqt程序为exe时，需要用multiprocessing.freeze_support()来防止无限开启进程。实际测试是可行的。
但当使用pystand打包时，在.int文件中调用主函数前使用freeze_support()。测试后无效果，即仍无限开启进程。
```
import main
from multiprocessing import freeze_support
freeze_support()
main.startwin()
```
请问有无解决方案？谢谢

**Comment by zty1122zty** [comment]
![图片1](https://github.com/skywind3000/PyStand/assets/108518151/239715b5-8aac-4a81-afcd-c726c5160e96)
官方文档中只支持了pyinstaller等打包方式

**Comment by myd7349** [comment]
看看这个帖子里提到的方法能不能帮到你：

https://github.com/skywind3000/PyStand/issues/21

**Comment by zty1122zty** [comment]
非常感谢。方法可行，问题已解决。
