### ISSUE TITLE
不支持python原生multiprocessing

### ISSUE THREAD

**Issue by yuanjunchn** [skywind3000/PyStand#82]
不知道是嵌入式python包的问题还是PyStand的问题，调试好的有multiprocessing的程序，放入PyStand中就会发生程序多开，程序也无法正确运行。

**Comment by myd7349** [comment]
看看这个帖子里提到的方法能不能帮到你：

https://github.com/skywind3000/PyStand/issues/21

**Comment by skywind3000** [comment]
能不能做个库，扔 site-packages 下面，给有需要的人 import 初始化一下？
