### ISSUE TITLE
能否支持Python3.4

### ISSUE THREAD

**Issue by yunluo** [skywind3000/PyStand#83]
因为还是会涉及到XP系统，就需要使用Python3.4了，但是在Python3.4这里没法使用，已经把Python3.4里面的python3.dll放到runtime目录了，还是不行，实际测试，直接点runtime的python.exe是可以正常启动的

**Comment by skywind3000** [comment]
还是不行？报错是啥？

**Comment by yunluo** [comment]
没有任何报错，我把int文件里面只留一个print sys.path

**Comment by skywind3000** [comment]
https://github.com/skywind3000/PyStand/releases/download/1.1.3/PyStand-py34.7z

给你做了一个了。

**Comment by yunluo** [comment]
大爱！

**Comment by skywind3000** [comment]
在我机器上确实可以运行 python3.4 的，但 pystand.exe 使用较新的编译器编译，是否能在 xp 下运行，我没环境测试不了，你可以确定下，如果 win 10/11 运行 pystand+py3.4 没问题，但 xp 下却不行的话，你找个支持 xp 的编译器重新编译下 pystand.exe 即可，或者试试 mingw 的版本。

**Comment by yunluo** [comment]
回复下使用情况，Win32版无法使用，显示不是标准win32程式，我拿的是32版，使用mingw32版提示缺msvcr100，我把这玩意放在runtime目录后实际运行没问题

**Comment by yunluo** [comment]
继续回复下使用情况，在高版本没问题，在XP版本出现一个问题，tcl库已经放在runtime根目录了，在windows 10可以顺利打开GUI，但是在XP出现找不到tcl的情况，我把runtime/tcl/tcl8.6加入了环境变量TCL_LABRARY和TK_LIBRARY就可以了

**Comment by skywind3000** [comment]
更正了一下 py34 版本的 PyStand.exe 和添加 msvcr100.dll，现在应该可以无修改直接运行于 XP 了：

https://github.com/skywind3000/PyStand/releases/download/1.1.3/PyStand-py34.7z
