### ISSUE TITLE
反馈1个bug/问题，不兼容Python3.10，弹窗报错

### ISSUE THREAD

**Issue by 750ti** [skywind3000/PyStand#85]
# 问题/症状
## 使用 Python3.10 ，打开软件启动弹窗报错

测试在Python3.8可以正常运行，后来换了Python3.10就无法运行了，其他更新的版本还未测试。  

打开 `PyStand.exe` 后弹窗提示 `ERROR`
```
ERROR
Cannot load python3.dll from:
D:\program\Python310\runtime
```

实际上 `runtime` 文件夹里面有 `python3.dll` 这个文件  
Python embed 版本号 `python-3.10.11-embed-amd64.zip`  
测试过排除了中英文路径问题   

---

尝试过将 `Python3.8` 的 `python3.dll` 复制过来替换，弹窗提示变成了  
```
Cannot find Py_Main() in:
D:\program\Python310\runtime\python3.dll
```

说明程序是能读取到这个问题，可能是不支持/不兼容。  

---

目前暂时解决办法是使用 bat 批处理启动

```
chcp 65001
@echo off
.\runtime\python.exe main.py
pause
```
---
2024年08月01日 04:24

**Comment by skywind3000** [comment]
你 pystand 和 runtime 里的架构要匹配，同是 32 位，或者同是 64 位，你是不是对应错了？把 64 位的 python 弄给 32 位的 pystand 去加载了？

**Comment by skywind3000** [comment]
这是常识问题
