### ISSUE TITLE
提供一个python3.11.9和PySide6.5.0精简版的x64版本

### ISSUE THREAD

**Issue by pass-wind** [skywind3000/PyStand#88]
[PyStand-py311-pyside6-lite.zip](https://github.com/user-attachments/files/16560778/PyStand-py311-pyside6-lite.zip)
文件后缀zip改为7z再解压（文件大小有限制只能这么干了😂）解压后60MB，runtime20MB。PySide6 40MB确实比py3.8+pyqt5或PySide2大多了。在script的main.py里放代码，script文件夹直接压缩，sys.path.append(os.path.abspath('script.egg/script'))这一行里就是压缩包里是个文件夹。然后改后缀为egg，删掉原来的script文件夹就好了

**Comment by makaspacex** [comment]
很不错的工作，可以稍微说下如何精简的以及精简了哪些内容吗 想学习下 因为我的python版本pyside版本不一样

**Comment by pass-wind** [comment]
> 很不错的工作，可以稍微说下如何精简的以及精简了哪些内容吗 想学习下 因为我的python版本pyside版本不一样

保留相同的目录和里面的同名文件就可以了

**Comment by zengzhengrong** [comment]
你的pyside6 很精简啊，我是用pyside6.7 请问怎么精简

**Comment by mengdeer589** [comment]
[https://github.com/mengdeer589/PythonSizeCruncher](url)
在此推荐一下我的项目，这是一个瘦身脚本，可以很轻易的做到打包后的文件精简

**Comment by pass-wind** [comment]
> 你的pyside6 很精简啊，我是用pyside6.7 请问怎么精简
你的包复制出来，保留和这个相同的文件

**Comment by pass-wind** [comment]
已经在用了，适合用了很多包，不知道怎么精简的时候> [https://github.com/mengdeer589/PythonSizeCruncher](url)
> 在此推荐一下我的项目，这是一个瘦身脚本，可以很轻易的做到打包后的文件精简

**Comment by zengzhengrong** [comment]
@pass-wind 
我从命令行启动pystand.exe 和 桌面双击启动 他们的启动速度差差了1倍， 命令行启动只要10s ，双击启动要20s，这怎么回事

**Comment by mengdeer589** [comment]
> @pass-wind 我从命令行启动pystand.exe 和 桌面双击启动 他们的启动速度差差了1倍， 命令行启动只要10s ，双击启动要20s，这怎么回事

第一次启动会慢很多。第二次及后面就正常了。另外，10s这个时间，可以优化程序了。如果是带界面的程序，建议先显示界面，然后再加载第三方库，可以用延迟加载，多线程加载等等。打包不要使用upx，不要搞成单文件，这两个操作都会增加启动时间。

**Comment by pass-wind** [comment]
> > @pass-wind 我从命令行启动pystand.exe 和 桌面双击启动 他们的启动速度差差了1倍， 命令行启动只要10s ，双击启动要20s，这怎么回事
> 
> 第一次启动会慢很多。第二次及后面就正常了。另外，10s这个时间，可以优化程序了。如果是带界面的程序，建议先显示界面，然后再加载第三方库，可以用延迟加载，多线程加载等等。打包不要使用upx，不要搞成单文件，这两个操作都会增加启动时间。

不知道你在说什么，这个项目只是搞了个python环境启动的快捷方式罢了，你说的所有问题都是python自己的问题，和这个项目无关，加载和upx和这个项目完全没有关系。还有我也不是项目作者、不是python作者，建议你提问题先找对人好吧。“第一次启动会慢很多。第二次及后面就正常了。”完全是python自己的原因。

**Comment by pass-wind** [comment]
> @pass-wind 我从命令行启动pystand.exe 和 桌面双击启动 他们的启动速度差差了1倍， 命令行启动只要10s ，双击启动要20s，这怎么回事

python自己的问题，你不用这个项目也是一样

**Comment by pass-wind** [comment]
> > @pass-wind 我从命令行启动pystand.exe 和 桌面双击启动 他们的启动速度差差了1倍， 命令行启动只要10s ，双击启动要20s，这怎么回事
> 
> 第一次启动会慢很多。第二次及后面就正常了。另外，10s这个时间，可以优化程序了。如果是带界面的程序，建议先显示界面，然后再加载第三方库，可以用延迟加载，多线程加载等等。打包不要使用upx，不要搞成单文件，这两个操作都会增加启动时间。

不好意思，把你俩看成一个人了。但确实和你说的打包什么的没有一点关系。
