### ISSUE TITLE
求助大佬，Traceback (most recent call last): File "<string>",line 38,in <module> ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by huang-cmd** [skywind3000/PyStand#91]
最新的release版本，点击pystand.exe，正常。pystand.ini就多加个空行，点保存。然后再运行pystand.exe 报错：
Traceback (most recent call last):
File "string",line 38,in module
ValueError: source code string cannot contain null bytes

**Comment by huang-cmd** [comment]
Traceback (most recent call last):
File "<string >“,line 38,in <module >
ValueError: source code string cannot contain null bytes

**Comment by myd7349** [comment]
猜测和 PyStand.int 的文本编码有关。

你用的什么文本编辑器？把它以 utf-8 编码保存后再试一下。

**Comment by huang-cmd** [comment]
我用的是windows自带的记事本，就是以UTF-8保存的，还是报错

**Comment by huang-cmd** [comment]
解决了，是公司软件加密的问题

**Comment by skywind3000** [comment]
我晕
